# server listen port
server_port: 8080
# db_user:password@tcp(localhost:3306)/my_db
dsn: "admin:qwer1234@tcp(localhost:3306)/mytestdb"
# json web token sign key
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
# json web token sign expiration in hours
jwt_expiration: 720